{
 "title": "DB Backup Controller",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(db_backup_controller_runner_started_at, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Next Scheduled Backup",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "db_backup_controller_next_scheduled_backup{exported_namespace=~\"$namespace\"}\n"
    }
   ]
  },
  {
   "title": "Last Successful Backup",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "db_backup_controller_last_successful_backup{exported_namespace=~\"$namespace\"} > 0"
    }
   ]
  },
  {
   "title": "Last Job Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "db_backup_controller_last_job_success{exported_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Stored Backups",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by (exported_namespace,name) (db_backup_controller_stored_backup_count{exported_namespace=~\"$namespace\"})",
     "legendFormat": "{{exported_namespace}} / {{name}}"
    }
   ]
  }
 ]
}