---

apiVersion: v2
name: db-backup-controller
version: '0.0.0'
kubeVersion: '>= 1.21.0'
description: Controller to provision database backup runners from CRD
type: application
maintainers:
  - name: Knut Ahlers
    email: ka@nect.com
appVersion: '0.0.0'

...
