---

# Source of the built Docker image using the Dockerfile in the repo root
image: 'ghcr.io/nectgmbh/db-backup-controller:latest'
# Specify imagePullPolicy for the deployment
imagePullPolicy: 'IfNotPresent'
# Enable / disable JSON format logging
jsonLog: true
# Valid log-levels for logrus (debug, info, error are used)
logLevel: 'info'
# Prefix for metrics exported in the controller
metricsPrefix: 'k8s_cert_monitor'
# How often to iterate through all existing backup definitions (1 / rescanInterval)
rescanInterval: 1h
# Registry configuration to access the image provided above
# (no configuration is added when registry is an empty string)
imagePullSecret:
  registry: ''
  user: ''
  password: ''
